services:
  postgres-db:
    restart: always
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=uzum_intern_database
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 5454
    ports:
      - 5454:5454/tcp
    depends_on:
      - postgres-db

  main-app:
    build: main-app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://uzum-intern-postgres-db:5432/uzum_intern_database
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - 8080:8080
    depends_on:
      - postgres-db

  notification-app:
    build: notification-app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://uzum-intern-postgres-db:5432/uzum_intern_database
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - 8081:8081
    depends_on:
      - postgres-db

  payment-app:
    build: payment-app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://uzum-intern-postgres-db:5432/uzum_intern_database
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - 8082:8082
    depends_on:
      - postgres-db
