services:
  main-app:
    build: main-app
    ports:
      - 8080:8080

  notification-app:
    build: notification-app
    ports:
      - 8081:8081

  payment-app:
    build: payment-app
    ports:
      - 8082:8082