server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: notification-app

env:
  port: 5672
  host: uzum-intern-rabbit
  username: uzum-user
  password: uzum-password
  queue: uzum-queue1
  exchange: uzum-exchange
  routingkey: uzum-rk